services:
  airflow-observer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - airflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  airflow-network:
    name: airflow_default
    external: true 